flaskFPL/main/routes.py
import time

import pandas as pd
from collections import Counter

from flaskFPL.main.functions import get_managers, get_league_data, get_amount_owed, \
    list_to_dict, latest_week, get_all_nth_lowest_players, \
    get_all_nth_lowest_comments, get_all_nth_lowest_comments_scorer, get_all_nth_lowest_players_scorer


from flask import render_template, flash, Blueprint
from flaskFPL.main.forms import EnterID

main = Blueprint('main', __name__)


@main.route('/', methods=['GET', 'POST'])
@main.route('/home', methods=['GET', 'POST'])
def home():
    form = EnterID()
    if form.validate_on_submit():
        league_data = get_league_data(form.league_id.data)
        # league name for showing on page
        league_name = league_data['league_name']
        flash(f"Retrieved data for {league_name}!", "success")

        # get basic league table
        df1 = league_data['league_table']

        # get the objects of each manager
        all_managers = get_managers(form.league_id.data)

        if "Scores" in form.scores_scorers.data:
            all_comments = get_all_nth_lowest_comments(all_managers, latest_week, (int(form.select_one.data) - 1))
            all_lowest = get_all_nth_lowest_players(all_managers, latest_week, (int(form.select_one.data) - 1))

            # calculates amount owed based on form input
            times_last = list_to_dict(all_lowest[0])
            amount_owed_last = get_amount_owed(times_last, form.amount_owed.data)

            if int(form.select_one.data) >= 2:
                all_second_lowest = all_lowest[1]
                times_second_last = list_to_dict(all_second_lowest)
                amount_owed_second_last = get_amount_owed(times_second_last, form.amount_owed_2.data)

                if int(form.select_one.data) == 3:
                    all_third_lowest = all_lowest[2]
                    times_third_last = list_to_dict(all_third_lowest)
                    amount_owed_third_last = get_amount_owed(times_third_last, form.amount_owed_3.data)

        # need to fix this section next and fix the SCORER functions
        else:

            all_comments = get_all_nth_lowest_comments_scorer(all_managers, latest_week, (int(form.select_one.data) - 1))
            all_lowest = get_all_nth_lowest_players_scorer(all_managers, latest_week, (int(form.select_one.data) - 1))

            times_last = list_to_dict(all_lowest[0])
            amount_owed_last = get_amount_owed(times_last, form.amount_owed.data)

            if int(form.select_one.data) >= 2:
                all_second_lowest = all_lowest[1]

                times_second_last = list_to_dict(all_second_lowest)

                amount_owed_second_last = get_amount_owed(times_second_last, form.amount_owed_2.data)

            if int(form.select_one.data) == 3:
                all_third_lowest = all_lowest[2]

                times_third_last = list_to_dict(all_third_lowest)

                amount_owed_third_last = get_amount_owed(times_third_last, form.amount_owed_3.data)

        if int(form.select_one.data) >= 1:
            amount_owed = amount_owed_last

            if int(form.select_one.data) >= 2:
                amount_owed = dict(Counter(amount_owed_last) + Counter(amount_owed_second_last))

                if int(form.select_one.data) >= 3:
                    amount_owed = dict(
                        Counter(amount_owed_last)
                        + Counter(amount_owed_second_last)
                        + Counter(amount_owed_third_last))

        # make a table based on amounts owed per player

        amount_owed_df = pd.DataFrame.from_dict(amount_owed_last, orient='index', columns=["Amount Owed"])

        # rename column
        amount_owed_df = amount_owed_df.rename_axis('Player Name')

        times_last_df = pd.DataFrame.from_dict(times_last, orient='index', columns=['Times Bottom'])

        # rename the column so it is same as df1
        times_last_df = times_last_df.rename_axis('Player Name')

        df = df1.merge(times_last_df, how="outer", right_on='Player Name', left_on='Player Name')

        if int(form.select_one.data) == 1:
            df = df.merge(amount_owed_df, how="outer", right_on='Player Name', left_on='Player Name')
            df = df.fillna(0)
            df = df.astype(
                {"ID": "int", "Rank": "int", "Total": "int", "Times Bottom": "int"})
        elif int(form.select_one.data) == 2:
            times_second_last_df = pd.DataFrame.from_dict(times_second_last, orient='index',
                                                          columns=['Times Second Bottom'])

            times_second_last_df = times_second_last_df.rename_axis('Player Name')

            df = df.merge(times_second_last_df, how="outer", right_on='Player Name', left_on='Player Name').fillna(0)

            amount_owed_second_df = pd.DataFrame.from_dict(amount_owed_second_last, orient='index',
                                                           columns=["Amount Owed"])

            # rename column
            amount_owed_second_df = amount_owed_second_df.rename_axis('Player Name')
            amount_owed_df = amount_owed_df.add(amount_owed_second_df, fill_value=0)

            df = df.merge(amount_owed_df, how="outer", right_on='Player Name', left_on='Player Name')

            df = df.fillna(0)

            df = df.astype(
                {"ID": "int", "Rank": "int", "Total": "int", "Times Bottom": "int", "Times Second Bottom": "int"})

        elif int(form.select_one.data) == 3:
            times_second_last_df = pd.DataFrame.from_dict(times_second_last, orient='index',
                                                          columns=['Times Second Bottom']).fillna(0)

            times_second_last_df = times_second_last_df.rename_axis('Player Name')

            df = df.merge(times_second_last_df, how="outer", right_on='Player Name', left_on='Player Name').fillna(0)

            amount_owed_second_df = pd.DataFrame.from_dict(amount_owed_second_last, orient='index',
                                                           columns=["Amount Owed"])

            # rename column
            amount_owed_second_df = amount_owed_second_df.rename_axis('Player Name')
            amount_owed_df = amount_owed_df.add(amount_owed_second_df, fill_value=0)

            times_third_last_df = pd.DataFrame.from_dict(times_third_last, orient='index',
                                                         columns=['Times Third Bottom']).fillna(0)

            times_third_last_df = times_third_last_df.rename_axis('Player Name')

            third_df = df.merge(times_third_last_df, how="outer", right_on='Player Name', left_on='Player Name').fillna(0)

            amount_owed_third_df = pd.DataFrame.from_dict(amount_owed_third_last, orient='index',
                                                          columns=["Amount Owed"])
            # rename column
            amount_owed_third_df = amount_owed_third_df.rename_axis('Player Name')
            amount_owed_df = amount_owed_df.add(amount_owed_third_df, fill_value=0)

            df = third_df.merge(amount_owed_df, how="outer",
                                right_on='Player Name', left_on='Player Name')
            df = df.fillna(0)

            df = df.astype(
                {"ID": "int", "Rank": "int", "Total": "int", "Times Bottom": "int", "Times Second Bottom": "int",
                 "Times Third Bottom": "int"})

        df = df.fillna(0)
        df = df[df["Player Name"].str.contains("Nobody") == False]
        df.drop("ID", inplace=True, axis=1)

        return render_template("fpl.html",
                               title=f"League Data for {league_name} after {latest_week} games",
                               tables=[df.to_html(classes=['data', 'table-striped'], justify="center", index=False)],
                               titles=df.columns.values, form=form, all_lowest=all_lowest,
                               amount_owed=amount_owed,
                               all_comments=all_comments, league_name=league_name)

    return render_template("home.html", title="Home", form=form)


@main.route('/about')
def about():
    return render_template("about.html", title="About")


@main.route('/leagueID')
def LeagueID():
    return render_template("LeagueIDGuide.html", title="How To Find Your League ID")

flaskFPL/templates/LeagueIDGuide.html
{% extends "layout.html" %}
    {% block content %}
        <div class="container">
            <h1>{{ title }}</h1>
        </div>
        <div class="content-section">
            To find your Leagues ID is pretty simple and can be done using any web browser.
            <br>
            <br>
            Begin by logging into your FPL account <a href="https://fantasy.premierleague.com/" target="_blank">here.</a>
            <br>
            <br>
            Once you are logged in, click on the "Leagues & Cups" tab which will display the leagues you are in.
            <br>
            <br>
            Click on the league you wish to see the ID for and then look in the address bar in your browser.
            <br>
            <br>
            Here you can see the address of the page you are on similar to this example:
            <br>
            "fantasy.premierleague.com/leagues/123456/standings/c"
            <br>
            <br>
            Your league ID is the number you see. In the example above the League ID is 123456.
            <br>
            <br>
            You can repeat this process to find any ID of the Leagues you are in.

        </div>
    {% endblock %}

flaskFPL/templates/about.html
{% extends "layout.html" %}
    {% block content %}
        <div class="container">
            <h1>{{ title }}</h1>
        </div>
        <div class="content-section">
            <p>
                Lost FPL was created as a quick way for me and my friends to see who had the lowest score of the week.<br><br>
                It is a way for us to keep Fantasy Premier League more interesting throughout the year as we battle to avoid paying fines for finishing with the bottom score each week.
                <br>
                <br>
                This makes players more engaged with updating their teams and continuing to play even though they may not be on the overall top spot.
            </p>
            <p>
                You can use this tool in a similar way and tailor it to suit your needs.
                <br>
                <br>
                All you need is your League ID and you can begin tracking who <strong>Lost FPL</strong> each week.
                <br>
                <br>
                A guide to find your League ID can be found <a href="{{ url_for('main.LeagueID') }}">here</a> or by clicking on the quick link <i>"How To Find Your League ID"</i>.
            </p>
            <p>
                There are a couple of options available to you when submitting the form.
                <br>
                <br>
                <strong>Scores</strong> or <strong>Scorers</strong>?
                <br>
                <br>
                <strong>Scores</strong> means it will return the players that have the bottom scorers ignoring how many players are included in this result.
                <br>
                <br>
                For example, You may have 2 players on 20 points, 2 players on 30 and 5 players on 40 points. If you select bottom 3 <strong>Scores</strong>, this will return
                a result telling you that 2 people were the bottom score, 2 people were 2nd lowest and 5 players were 3rd lowest.
                <br>
                <br>
                <strong>Scorers</strong> will return the bottom amount of scorers in your selection.
                <br>
                <br>
                Taking the same example as above, if you ask for the bottom 3 <strong>Scorers</strong> it will only return you a result saying that the 2 players on 20 points were bottom
                and the 2 players on 30 points were 2nd bottom. It will tell you that nobody came 3rd bottom that week as the number of players you asked for had already been satisfied.
            </p>

        </div>
    {% endblock %}

flaskFPL/templates/fpl.html
{% extends "layout.html" %}
    {% block content %}
    <div class="content-section col text-center">
        <h1><strong>{{ title }}</strong></h1>
        <div class="container">
            <div class="row justify-content-center">
                <div class="slide-content" style="overflow-x: scroll">
                    <table class="table center">
                        {% for table in tables %}
                            {{ table|safe }}
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>


        <div class="col">
            <h3>Here is how much each player owes</h3>
            {% for key, value in amount_owed.items() %}
                {% if key != "Nobody" %}
                    <strong>{{ key }} : {{ value }}</strong>
                    <br>
                {% endif %}
            {% endfor %}
        </div>
        <div class="pt-3 ">
            <p>Click the "Show breakdown" buttons to toggle between hiding and showing the weekly lowest scorers</p>
        </div>
            <div class="container pt-3">
                <button onclick="showResults1()">Show Lowest Breakdown</button>
                <div id="lowest" style="display : none">
                    <h3><strong>Here is a breakdown of the lowest player of each week!</strong></h3>
                        {% for l in all_comments[0] %}
                            <p>{{ l }}</p>
                        {% endfor %}
                </div>
            </div>

        {% if all_comments[1] %}
        <div class="container pt-3">
            <button onclick="showResults2()">Show Second Lowest Breakdown</button>

            <div id="2ndlowest" style="display : none">
                <h3><strong>Here is a breakdown of the 2nd lowest player of each week!</strong></h3>
                    {% for i in all_comments[1] %}
                        <p>{{ i }}</p>
                    {% endfor %}
            </div>
        </div>
        {% endif %}



        {% if all_comments[2] %}
        <div class="container pt-3">
            <button onclick="showResults3()">Show Third Lowest Breakdown</button>

            <div id="3rdlowest" style="display : none">
                <h3><strong>Here is a breakdown of the 3rd lowest player of each week!</strong></h3>
                    {% for j in all_comments[2] %}
                        <p>{{ j }}</p>
                    {% endfor %}
            </div>
        </div>
        {% endif %}


    </div>

    <script>
    function showResults1() {
      var x = document.getElementById("lowest");
      if (x.style.display === "none") {
        x.style.display = "block";
      } else {
        x.style.display = "none";
      }
    }
    </script>
    <script>
    function showResults2() {
      var x = document.getElementById("2ndlowest");
      if (x.style.display === "none") {
        x.style.display = "block";
      } else {
        x.style.display = "none";
      }
    }
    </script>
    <script>
    function showResults3() {
      var x = document.getElementById("3rdlowest");
      if (x.style.display === "none") {
        x.style.display = "block";
      } else {
        x.style.display = "none";
      }
    }
    </script>
    {% endblock content %}

flaskFPL/templates/home.html
{% extends "layout.html" %}
    {% block content %}
<div class="content-section">
          <form method ="POST" action="">
              {{ form.hidden_tag() }}
              <fieldset class="form-group">
                  <legend class="border-bottom mb-4" >LOST FPL - Enter your required selections</legend>
                  <div class="form-group">
                      {{ form.league_id.label(class="form-control-label") }} - Find it <a href="{{ url_for('main.LeagueID') }}">here</a>

                      {% if form.league_id.errors %}
                        {{ form.league_id(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.league_id.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                            {{ form.league_id(class="form-control form-control-lg") }}
                      {% endif %}
                  </div>
		  <div class="form-group">
                    {{ form.scores_scorers.label(class="form-control-label") }}

                    {% if form.scores_scorers.errors %}
                    {{ form.scores_scorers(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.scores_scorers.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                      {{ form.scores_scorers(class="form-control form-control-lg") }}
                    {% endif %}
                  </div>
                  <div class="form-group">
                  {{ form.select_one.label(class="form-control-label") }}

                  {% if form.select_one.errors %}
                    {{ form.select_one(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.select_one.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.select_one(class="form-control form-control-lg") }}
                  {% endif %}
                </div>
                <div class="form-group">
                  {{ form.amount_owed.label(class="form-control-label") }}

                  {% if form.amount_owed.errors %}
                    {{ form.amount_owed(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form2.amount_owed.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.amount_owed(class="form-control form-control-lg") }}
                  {% endif %}
                </div>
                <div class="form-group">
                  {{ form.amount_owed_2.label(class="form-control-label") }}

                  {% if form.amount_owed_2.errors %}
                    {{ form.amount_owed_2(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.amount_owed_2.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.amount_owed_2(class="form-control form-control-lg") }}
                  {% endif %}
                </div>
                <div class="form-group">
                  {{ form.amount_owed_3.label(class="form-control-label") }}

                  {% if form.amount_owed_3.errors %}
                    {{ form.amount_owed_3(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.amount_owed_3.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.amount_owed_3(class="form-control form-control-lg") }}
                  {% endif %}
                </div>
              </fieldset>
              <div class="form-group pt-3">
                  {{ form.submit(class="btn btn-outline-info") }}
              </div>
          </form>
</div>
    {% endblock content %}

flaskFPL/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>LOST FPL - {{ title }}</title>
    {% else %}
        <title>LOST FPL</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">LOST FPL</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>

            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" style="padding-bottom:100px; width:100%;">
      <div class="row">
        <div class="m-4 center col">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert text-center alert-{{ category }} w-100">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}

          {% endblock %}
        </div>
        <div class="ml-4 mr-4 col-md-3 mt-4 col-md-pull-right col-lg-3 center col-lg-pull-right">
          <div class="content-section">
            <h3>LOST FPL Quick Links</h3>
            <p class='text-muted'>Useful links to other sites and pages.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light"><a href="https://fantasy.premierleague.com/" target="_blank">Fantasy Premier League</a></li>
                <li class="list-group-item list-group-item-light"><a href="https://fantasy.premierleague.com/fixtures" target="_blank">Fixtures</a></li>
                <li class="list-group-item list-group-item-light"><a href="{{ url_for('main.LeagueID')}}">How To Find Your League ID</a></li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

       <!-- Footer -->
<footer class="page-footer fixed-bottom bg-steel footer-expand-md" style="color: #cbd5db">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3"><p>Designed and Developed by:</p>
    <a style="color: #cbd5db" href="https://www.linkedin.com/in/shaun-mabin-862bb5104" target="_blank"> Shaun Mabin</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>



</body>
</html>